name: Deploy MkDocs Site from Search Branch

on:
  push:
    branches:
      - search  # This sets it to trigger on changes to the 'search' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  

      - name: Build the MkDocs site
        run: mkdocs build --verbose
        working-directory: mkdocs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mkdocs/site
          publish_branch: gh-pages  # This pushes the build to the 'gh-pages' branch
